# Generated by Django 3.2.4 on 2021-09-09 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210909_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='requested',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Request Accepted', 'Request Accepted'), ('Request Denied', 'Request Denied')], default='Requested', max_length=100),
        ),
    ]
