# Generated by Django 3.2.4 on 2021-09-20 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='requested',
            field=models.CharField(choices=[('Requested', 'Requested'), ('Request Accepted', 'Request Accepted'), ('Request Denied', 'Request Denied'), ('Request canceled', 'Request canceled')], default='Requested', max_length=100),
        ),
    ]
