# Generated by Django 3.2.4 on 2021-09-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='house',
            field=models.CharField(max_length=100),
        ),
    ]
