# Generated by Django 3.2.4 on 2021-09-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_alter_payment_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
