# Generated by Django 3.2.4 on 2021-10-06 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_auto_20211004_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(blank=True, default='yenePay', max_length=100),
        ),
    ]
