# Generated by Django 3.2.4 on 2021-10-06 23:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('payment_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
