# Generated by Django 3.2.4 on 2021-10-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_alter_payment_invoice_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_invoice',
            name='confirmation',
            field=models.BooleanField(default=False),
        ),
    ]
