# Generated by Django 3.2.4 on 2021-08-26 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_address2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='address2',
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
