# Generated by Django 3.2.4 on 2021-09-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20210826_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='is_for_rent',
        ),
        migrations.AddField(
            model_name='listing',
            name='listed_for',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_term',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='listing',
            name='property',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
