# Generated by Django 3.2.4 on 2021-09-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_listing_realtor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='longitude',
        ),
    ]
